media:
  input: public/uploads
  output: /uploads

content:
  - name: sessions
    label: Sessions TEST
    type: collection
    path: src/content/sessions
    filename: "{fields.title}.md"
    fields:
      - name: draft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
        required: false
      - name: locationName
        label: Location Name
        type: string
        required: true
      - name: address
        label: Address
        type: string
        required: true
      - name: googleMapsLink
        label: Google Maps Link
        type: string
        hidden: true
        required: false
      - name: latitude
        label: Latitude
        type: number
        hidden: true
      - name: longitude
        label: Longitude
        type: number
        hidden: true
      - name: alerts
        label: Alerts Line
        type: text
        hidden: true
        required: true
      - name: generalInfo
        label: General Info
        type: rich-text
        required: false
      - name: startTime
        label: Start Time
        type: string
      - name: endTime
        label: End Time
        type: string
      - name: schedule
        label: Schedule
        type: select
        options:
          - weekly
          - monthly
          - other
      - name: day
        label: Day
        type: select
        options:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
          - other
      - name: description
        label: Description
        type: text
        hidden: true
  - name: settings
    label: Settings
    type: file
    path: src/content/settings/settings.md
    fields:
      - name: footerNote
        label: Footer Note
        type: rich-text
        required: true
        options:
          format: markdown
      - name: aboutTitle
        label: About Title
        type: rich-text
        required: true
        options:
          format: markdown
      - name: aboutIntro
        label: About Intro
        type: rich-text
        required: true
        options:
          format: markdown
      - name: aboutSupport
        label: About Support Line
        type: rich-text
        required: false
        options:
          format: markdown
      - name: aboutFooter
        label: About Footer
        type: rich-text
        required: false
        options:
          format: markdown
